#line 2 "lex.c"

#line 4 "lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[353] =
    {   0,
        0,    0,   21,   21,    0,    0,   27,   20,    2,    1,
       20,   20,   12,    7,   15,    7,    7,    7,   20,    7,
        7,    5,    7,    7,    7,    7,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    7,    7,   21,   22,   21,   21,
       25,   26,   24,   24,   24,   24,    1,    0,   13,    0,
       12,   15,   10,    8,    9,    0,    0,    5,   17,   16,
        5,   12,    7,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    3,    4,    4,    4,    4,    4,    3,    4,
        4,    4,    4,    4,    4,    3,    3,    4,    4,    4,

        4,    4,    4,    3,    4,    4,    4,    4,   21,   22,
       21,   23,   21,   24,   15,   10,    0,   19,    0,    0,
        6,    0,    0,    0,    6,    4,    4,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    3,    4,    3,
        4,    4,    4,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    3,    4,    4,    4,   15,   10,    0,
        6,    0,   17,    0,   16,   18,   18,   12,    4,    4,
        4,    4,    4,    3,    4,    3,    4,    4,    4,    3,
        4,    4,    4,    4,    4,    4,    3,    3,    4,    4,
        4,    3,    4,    3,    4,   15,   10,    0,    0,   18,

        0,   12,    4,    4,    3,    3,    3,    4,    3,    4,
        4,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    3,    3,   15,   10,    0,   18,    4,    4,    4,
        4,    3,    4,    4,    4,    4,    3,    4,    4,    3,
        3,    4,   15,   10,    0,    4,    4,    4,    4,    4,
        3,    3,    4,    3,    4,    3,   15,   10,    0,    4,
        3,    3,    3,    3,    3,    3,   15,   10,    0,    4,
       15,   10,    0,    4,   15,   10,    0,    4,   15,   10,
        0,    4,   15,   10,    0,    4,   15,   10,    0,    4,
       15,   10,    0,    4,   15,   10,    0,   11,   15,   10,

        0,   11,   15,   10,    0,   15,   10,    0,   15,   10,
        0,   15,   10,    0,   15,   10,    0,   15,   10,    0,
       15,   10,    0,   15,   10,    0,   15,   10,    0,   15,
       10,    0,   15,   10,    0,   15,   10,    0,   15,   10,
        0,   15,   10,    0,   15,   10,    0,   15,   14,    0,
        0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    6,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   39,   46,   39,
       47,    1,   48,    6,   39,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   39,   65,   66,   67,   68,   69,   70,   39,
       71,   39,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    1,    1,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[438] =
    {   0,
        0,    0,   73,   75,   78,   90,  822,  947,  947,  947,
      814,   75,    0,  947,  808,  800,  947,   77,   88,   92,
      793,   99,  784,   97,  783,   74,   84,   95,  105,   76,
       95,  113,    0,  108,   95,   96,  130,  150,   75,  111,
      141,  147,  120,  149,  947,  947,    0,  947,  796,  181,
      947,  947,  947,  174,  777,  180,  947,  122,  177,  785,
        0,  784,  779,  776,  947,  196,  764,  194,  196,  199,
      202,  210,  947,    0,  177,  194,  188,  201,  204,  191,
      194,  200,  195,  198,  214,  204,  204,  206,    0,  203,
      212,  224,  217,  212,  229,    0,    0,  228,  248,  235,

      237,  235,  251,    0,  240,  250,  243,  253,    0,  947,
      275,  947,  278,  947,  772,  767,  766,  947,  278,  297,
      279,  301,  106,  752,  302,    0,  257,    0,  278,  271,
      298,  295,  297,  297,  292,  301,  299,    0,  307,    0,
      306,  308,  307,    0,    0,    0,  310,  309,  319,  300,
      312,  311,  307,    0,  310,  320,  318,  760,  755,  754,
      359,  358,  363,  366,  367,  360,  371,  385,    0,  332,
      343,  355,  360,    0,  364,    0,  359,  365,  369,    0,
      363,  364,  378,  378,  383,  371,    0,    0,  373,  384,
      389,    0,  400,    0,  401,  749,  748,  743,  435,  415,

      422,  428,    0,  395,    0,    0,    0,  405,    0,  410,
      429,    0,  426,  431,  423,  423,  420,  441,  434,  439,
      440,    0,  436,  742,  737,  736,  461,    0,  431,  448,
      431,    0,  438,  437,  437,  440,    0,  454,  457,    0,
        0,  458,  731,  730,  725,    0,  473,  469,  479,  471,
        0,    0,  482,    0,  468,    0,  724,  719,  718,    0,
        0,    0,    0,    0,    0,    0,  713,  712,  707,    0,
      706,  701,  700,    0,  695,  694,  689,    0,  688,  683,
      682,    0,  677,  676,  671,    0,  670,  665,  664,    0,
      659,  658,  653,    0,  652,  647,  646,    0,  641,  640,

      635,    0,  634,  629,  628,  623,  622,  617,  616,  611,
      610,  605,  604,  599,  598,  593,  592,  587,  586,  581,
      580,  575,  574,  569,  568,  562,  559,  556,  551,  550,
      547,  542,  541,  523,  522,  520,  519,  517,  516,  515,
      514,  513,  510,  509,  508,  505,  504,  503,  501,  453,
      402,  947,  535,  541,  547,  550,  556,  398,  562,  568,
      574,  348,  580,  586,  333,  592,  598,  297,  604,  610,
      276,  616,  622,  231,  628,  634,  226,  640,  646,  193,
      652,  658,  182,  664,  670,  174,  676,  682,  169,  688,
      694,  139,  700,  706,  131,  712,  718,  119,  724,  730,

       85,  736,  742,   76,  748,  754,  760,  766,  772,  778,
      784,  790,  796,  802,  808,  814,  820,  826,  832,  838,
      844,  850,  856,  862,  868,  874,  880,  886,  892,  898,
      904,  910,  916,  922,  928,  934,  940
    } ;

static const flex_int16_t yy_def[438] =
    {   0,
      352,    1,  353,  353,  354,  354,  352,  352,  352,  352,
      352,  355,  356,  352,  357,  352,  352,  352,  352,  352,
      352,  356,  352,  352,  352,  352,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  352,  352,  359,  352,  359,  360,
      352,  352,  352,  352,  352,  352,  352,  355,  355,  352,
      356,  361,  352,  352,  352,  352,  352,  352,  352,  352,
      356,  356,  352,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  359,  352,
      360,  352,  360,  352,  363,  352,  364,  352,  352,  352,
      352,  352,  352,  352,  356,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  366,  352,  367,
      352,  352,  352,  352,  352,  352,  352,  356,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  369,  352,  370,  352,  352,

      352,  356,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  372,  352,  373,  352,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  375,  352,  376,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  378,  352,  379,  380,
      380,  380,  380,  380,  380,  380,  381,  352,  382,  383,
      384,  352,  385,  386,  387,  352,  388,  389,  390,  352,
      391,  392,  393,  352,  394,  395,  396,  352,  397,  398,
      399,  352,  400,  401,  402,  352,  403,  404,  405,  352,

      406,  404,  407,  352,  408,  409,  352,  410,  411,  352,
      412,  413,  352,  414,  415,  352,  416,  417,  352,  418,
      419,  352,  420,  421,  352,  422,  423,  352,  424,  425,
      352,  426,  427,  352,  428,  429,  352,  430,  431,  352,
      432,  433,  352,  434,  435,  352,  436,  435,  352,  437,
      437,    0,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352
    } ;

static const flex_int16_t yy_nxt[1023] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   14,   20,   21,   14,   22,   23,   14,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   33,
       34,   33,   33,   35,   36,   37,   38,   39,   33,   40,
       41,   42,   33,   43,   44,   33,   45,   45,   27,   28,
       29,   30,   31,   32,   33,   33,   34,   33,   33,   35,
       36,   37,   38,   39,   40,   41,   42,   33,   43,   44,
       33,   46,    8,   46,   14,   48,   49,   48,   49,   59,
       52,  302,   60,   50,   53,   50,   65,   66,   53,   53,
      298,   53,   52,   53,   73,   73,   53,   54,   55,   56,

       53,   53,   67,   53,   68,   53,   67,   75,   68,   54,
       55,   56,   83,   70,   98,   71,   73,   73,   73,   76,
      124,   78,  161,   77,  294,   72,   59,   81,   84,   60,
       85,   91,   92,   75,   79,   89,  290,   99,   83,   98,
       80,   82,  105,   90,  286,   76,   86,   78,   77,   87,
       53,   72,   53,   81,   84,   88,   85,   91,   92,   79,
       93,   89,   53,   99,   53,   80,   94,   82,  105,   90,
      100,  101,   86,   95,  282,   87,  103,   96,  106,  278,
       88,   59,  102,  104,   60,  107,   93,  274,  108,   97,
      112,  113,   94,  114,  114,  114,  100,  101,  270,   95,

      114,  114,  103,   96,  106,   65,   66,  102,   70,  104,
       68,  107,   69,  108,   97,  121,   70,  127,   71,  128,
      119,  123,  120,  123,  124,  122,  125,  129,   72,  130,
      131,  260,  132,  133,  134,  135,  246,  136,  137,  138,
      139,  141,  127,  140,  142,  128,  119,  143,  120,  144,
      145,  122,  129,  146,   72,  130,  131,  132,  133,  134,
      147,  135,  136,  137,  148,  138,  139,  141,  140,  142,
      149,  150,  151,  143,  152,  144,  145,  153,  146,  154,
      155,  228,  156,  157,  352,  352,  147,  112,  113,  123,
      148,  123,  124,  170,  161,  121,  149,  150,  151,  152,

      171,  172,  203,  153,  154,  119,  155,  156,  162,  157,
      162,  124,  164,  163,  164,  124,  167,  165,  125,  170,
      173,  174,  175,  176,  179,  180,  171,  172,  168,  181,
      182,  119,  177,  178,  183,  184,  185,  186,  169,  189,
      190,  191,  192,  193,  187,  194,  173,  174,  175,  176,
      179,  180,  188,  126,  168,  181,  182,  177,  178,  195,
      183,  184,  185,  186,  189,  204,  190,  191,  192,  193,
      187,  194,  124,  167,  163,  161,  166,  167,  188,  163,
      124,  167,  165,  165,  195,  199,  199,  200,  205,  199,
      206,  204,  207,  199,  208,  210,  201,  199,  201,  124,

      209,  202,  211,   74,  212,  213,  214,  217,  215,  349,
      218,  199,  199,  205,  219,  199,  206,  220,  207,  199,
      208,  210,  216,  199,  221,  209,  222,  223,  211,  212,
      213,  200,  214,  217,  215,  218,  124,  229,  227,  219,
      230,  199,  167,  220,  202,  231,  201,  216,  201,  124,
      221,  227,  222,  223,  168,  232,  233,  234,  235,  236,
      349,  237,  229,  238,  239,  240,  230,  199,  241,  242,
      248,  231,  247,  249,  250,  167,  251,  227,  252,  253,
      168,  232,  233,  234,  235,  236,  237,  199,  254,  238,
      239,  240,  255,  256,  241,  242,  248,  247,  249,  261,

      250,  251,  262,  252,  253,  263,  264,  265,  351,  266,
      349,  346,  350,  199,  254,  349,  343,  347,  255,  256,
      346,  340,  344,  343,  337,  261,  341,  340,  262,  334,
      338,  263,  264,  265,  266,   47,   47,   47,   47,   47,
       47,   51,   51,   51,   51,   51,   51,   58,  337,  331,
       58,   58,   58,   61,  335,   61,   62,  334,  328,   62,
       62,   62,  109,  332,  109,  109,  331,  109,  111,  325,
      111,  111,  111,  111,  115,  329,  328,  115,  115,  115,
      158,  322,  326,  158,  158,  158,  160,  325,  319,  160,
      160,  160,  196,  323,  322,  196,  196,  196,  198,  316,

      320,  198,  198,  198,  224,  319,  313,  224,  224,  224,
      226,  317,  316,  226,  226,  226,  243,  310,  314,  243,
      243,  243,  245,  313,  307,  245,  245,  245,  257,  311,
      310,  257,  257,  257,  259,  304,  308,  259,  259,  259,
      267,  307,  300,  267,  267,  267,  269,  305,  304,  269,
      269,  269,  271,  296,  301,  271,  271,  271,  273,  300,
      292,  273,  273,  273,  275,  297,  296,  275,  275,  275,
      277,  288,  293,  277,  277,  277,  279,  292,  284,  279,
      279,  279,  281,  289,  288,  281,  281,  281,  283,  280,
      285,  283,  283,  283,  285,  284,  276,  285,  285,  285,

      287,  281,  280,  287,  287,  287,  289,  272,  277,  289,
      289,  289,  291,  276,  268,  291,  291,  291,  293,  273,
      272,  293,  293,  293,  295,  258,  269,  295,  295,  295,
      297,  268,  244,  297,  297,  297,  299,  259,  258,  299,
      299,  299,  301,  225,  245,  301,  301,  301,  303,  244,
      197,  303,  303,  303,  305,  226,  225,  305,  305,  305,
      306,  159,  198,  306,  306,  306,  308,  197,  166,  308,
      308,  308,  309,  116,  160,  309,  309,  309,  311,  159,
       69,  311,  311,  311,  312,  118,  117,  312,  312,  312,
      314,  116,   58,  314,  314,  314,  315,  114,  110,  315,

      315,  315,  317,   73,   73,  317,  317,  317,  318,   69,
       64,  318,  318,  318,  320,   63,   57,  320,  320,  320,
      321,  352,  352,  321,  321,  321,  323,  352,  352,  323,
      323,  323,  324,  352,  352,  324,  324,  324,  326,  352,
      352,  326,  326,  326,  327,  352,  352,  327,  327,  327,
      329,  352,  352,  329,  329,  329,  330,  352,  352,  330,
      330,  330,  332,  352,  352,  332,  332,  332,  333,  352,
      352,  333,  333,  333,  335,  352,  352,  335,  335,  335,
      336,  352,  352,  336,  336,  336,  338,  352,  352,  338,
      338,  338,  339,  352,  352,  339,  339,  339,  341,  352,

      352,  341,  341,  341,  342,  352,  352,  342,  342,  342,
      344,  352,  352,  344,  344,  344,  345,  352,  352,  345,
      345,  345,  347,  352,  352,  347,  347,  347,  348,  352,
      352,  348,  348,  348,  350,  352,  352,  350,  350,  350,
      351,  352,  352,  351,  351,  351,    7,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352
    } ;

static const flex_int16_t yy_chk[1023] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,   12,
        5,  404,   12,    3,    5,    4,   18,   18,    5,    5,
      401,    5,    6,    5,   26,   26,    6,    5,    5,    5,

        6,    6,   19,    6,   19,    6,   20,   27,   20,    6,
        6,    6,   30,   22,   39,   22,   24,   24,   24,   27,
      123,   28,  123,   27,  398,   22,   58,   29,   31,   58,
       31,   35,   36,   27,   28,   34,  395,   40,   30,   39,
       28,   29,   43,   34,  392,   27,   32,   28,   27,   32,
        5,   22,    5,   29,   31,   32,   31,   35,   36,   28,
       37,   34,    6,   40,    6,   28,   37,   29,   43,   34,
       41,   41,   32,   38,  389,   32,   42,   38,   44,  386,
       32,   59,   41,   42,   59,   44,   37,  383,   44,   38,
       50,   50,   37,   54,   54,   54,   41,   41,  380,   38,

       56,   56,   42,   38,   44,   66,   66,   41,   68,   42,
       68,   44,   69,   44,   38,   70,   71,   75,   71,   76,
       68,   72,   69,   72,   72,   70,   72,   77,   71,   78,
       79,  377,   80,   81,   81,   82,  374,   83,   84,   85,
       86,   88,   75,   87,   90,   76,   68,   91,   69,   92,
       93,   70,   77,   94,   71,   78,   79,   80,   81,   81,
       95,   82,   83,   84,   98,   85,   86,   88,   87,   90,
       99,  100,  101,   91,  102,   92,   93,  103,   94,  105,
      106,  371,  107,  108,  111,  111,   95,  113,  113,  119,
       98,  119,  119,  127,  119,  121,   99,  100,  101,  102,

      129,  130,  368,  103,  105,  121,  106,  107,  120,  108,
      120,  120,  122,  120,  122,  122,  125,  122,  125,  127,
      131,  132,  133,  134,  136,  137,  129,  130,  125,  139,
      141,  121,  135,  135,  142,  143,  147,  148,  365,  150,
      151,  152,  153,  155,  149,  156,  131,  132,  133,  134,
      136,  137,  149,  362,  125,  139,  141,  135,  135,  157,
      142,  143,  147,  148,  150,  170,  151,  152,  153,  155,
      149,  156,  162,  161,  162,  161,  166,  163,  149,  163,
      164,  165,  164,  165,  157,  161,  166,  167,  171,  163,
      172,  170,  173,  165,  175,  178,  168,  167,  168,  168,

      177,  168,  179,  358,  181,  182,  183,  185,  184,  351,
      186,  161,  166,  171,  189,  163,  172,  190,  173,  165,
      175,  178,  184,  167,  191,  177,  193,  195,  179,  181,
      182,  200,  183,  185,  184,  186,  201,  204,  201,  189,
      208,  200,  202,  190,  202,  210,  199,  184,  199,  199,
      191,  199,  193,  195,  202,  211,  213,  214,  215,  216,
      350,  217,  204,  218,  219,  220,  208,  200,  221,  223,
      230,  210,  229,  231,  233,  227,  234,  227,  235,  236,
      202,  211,  213,  214,  215,  216,  217,  227,  238,  218,
      219,  220,  239,  242,  221,  223,  230,  229,  231,  247,

      233,  234,  248,  235,  236,  249,  250,  253,  349,  255,
      348,  347,  346,  227,  238,  345,  344,  343,  239,  242,
      342,  341,  340,  339,  338,  247,  337,  336,  248,  335,
      334,  249,  250,  253,  255,  353,  353,  353,  353,  353,
      353,  354,  354,  354,  354,  354,  354,  355,  333,  332,
      355,  355,  355,  356,  331,  356,  357,  330,  329,  357,
      357,  357,  359,  328,  359,  359,  327,  359,  360,  326,
      360,  360,  360,  360,  361,  325,  324,  361,  361,  361,
      363,  323,  322,  363,  363,  363,  364,  321,  320,  364,
      364,  364,  366,  319,  318,  366,  366,  366,  367,  317,

      316,  367,  367,  367,  369,  315,  314,  369,  369,  369,
      370,  313,  312,  370,  370,  370,  372,  311,  310,  372,
      372,  372,  373,  309,  308,  373,  373,  373,  375,  307,
      306,  375,  375,  375,  376,  305,  304,  376,  376,  376,
      378,  303,  301,  378,  378,  378,  379,  300,  299,  379,
      379,  379,  381,  297,  296,  381,  381,  381,  382,  295,
      293,  382,  382,  382,  384,  292,  291,  384,  384,  384,
      385,  289,  288,  385,  385,  385,  387,  287,  285,  387,
      387,  387,  388,  284,  283,  388,  388,  388,  390,  281,
      280,  390,  390,  390,  391,  279,  277,  391,  391,  391,

      393,  276,  275,  393,  393,  393,  394,  273,  272,  394,
      394,  394,  396,  271,  269,  396,  396,  396,  397,  268,
      267,  397,  397,  397,  399,  259,  258,  399,  399,  399,
      400,  257,  245,  400,  400,  400,  402,  244,  243,  402,
      402,  402,  403,  226,  225,  403,  403,  403,  405,  224,
      198,  405,  405,  405,  406,  197,  196,  406,  406,  406,
      407,  160,  159,  407,  407,  407,  408,  158,  124,  408,
      408,  408,  409,  117,  116,  409,  409,  409,  410,  115,
       67,  410,  410,  410,  411,   64,   63,  411,  411,  411,
      412,   62,   60,  412,  412,  412,  413,   55,   49,  413,

      413,  413,  414,   25,   23,  414,  414,  414,  415,   21,
       16,  415,  415,  415,  416,   15,   11,  416,  416,  416,
      417,    7,    0,  417,  417,  417,  418,    0,    0,  418,
      418,  418,  419,    0,    0,  419,  419,  419,  420,    0,
        0,  420,  420,  420,  421,    0,    0,  421,  421,  421,
      422,    0,    0,  422,  422,  422,  423,    0,    0,  423,
      423,  423,  424,    0,    0,  424,  424,  424,  425,    0,
        0,  425,  425,  425,  426,    0,    0,  426,  426,  426,
      427,    0,    0,  427,  427,  427,  428,    0,    0,  428,
      428,  428,  429,    0,    0,  429,  429,  429,  430,    0,

        0,  430,  430,  430,  431,    0,    0,  431,  431,  431,
      432,    0,    0,  432,  432,  432,  433,    0,    0,  433,
      433,  433,  434,    0,    0,  434,  434,  434,  435,    0,
        0,  435,  435,  435,  436,    0,    0,  436,  436,  436,
      437,    0,    0,  437,  437,  437,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "B103040012.l"
#line 2 "B103040012.l"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "symbol_table.h"

#define KNRM  "\x1B[0m"
#define KRED  "\x1B[31m"
#define KGRN  "\x1B[32m"
#define KYEL  "\x1B[33m"
#define KBLU  "\x1B[34m"
#define KMAG  "\x1B[35m"
#define KCYN  "\x1B[36m"
#define KWHT  "\x1B[37m"

unsigned long _line = 1, _pos = 1;

void inform(unsigned long l, unsigned long p, const char* token, const char* type, const char* complement);
void color(const char* c, char* s);
#line 827 "lex.c"
/* float [+-]?[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)? */
/*comments \(\*({comments}|.|\r?\n)?\*\)*/
/* flex cannot “balance” parentheses to an arbitrary degree: https://www.cs.virginia.edu/~cr4bd/flex-manual/Does-flex-support-recursive-pattern-definitions_003f.html */
/* incompleted_string_dquote \"[^;\r\n\ ]*|[^;\r\n\ ]*\" */
/* incompleted_string \'[^)';\r\n\ ]*|[^(';\r\n\ ]*\' */
/* float_with_multi_frac {int}(\.{unsigned}?([eE]({float_without_frac_exp}|{float_without_int_exp}|{float_without_exp}))?){2,} */

#line 835 "lex.c"

#define INITIAL 0
#define COMMENT_STATE 1
#define NUMERIC_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 89 "B103040012.l"


#line 1057 "lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 353 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 947 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 92 "B103040012.l"
{
        ++_line;
        _pos = 1;
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "B103040012.l"
{
        _pos += yyleng;
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 101 "B103040012.l"
{
        char type[50] = "reserved word";
        color(KGRN, type);

        inform(_line, _pos, yytext, type, "");
        _pos += yyleng;
    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 109 "B103040012.l"
{
        char type[50] = "identity";
        color(KYEL, type);

        inform(_line, _pos, yytext, type, "");
        _pos += yyleng;
        insert(yytext);
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "B103040012.l"
{
        inform(_line, _pos, yytext, "integer", "");
        _pos += yyleng;
        BEGIN(NUMERIC_STATE);
    }
	YY_BREAK
/*
    ({int}[\+\-\*\/]{int}) {
        regex_t preg;
        regcomp(&preg, "[+-]?[0-9]+", REG_EXTENDED);
        char text[200], s[200];
        memcpy(text, yytext, (sizeof(char) * 200 > strlen(yytext) ? strlen(yytext) : sizeof(char) * 200));
        regmatch_t matchptr[1];
        int status = regexec(&preg, text, 1, matchptr, 0);
        size_t len_s = 0;
        if (status == 0)
        {
            len_s = matchptr[0].rm_eo - matchptr[0].rm_so;
            memcpy(s, text + matchptr[0].rm_so, len_s * sizeof(char));
        }
        s[len_s] = '\0';
        inform(_line, _pos, s, "integer", "");
        _pos += len_s;
        s[0] = text[matchptr[0].rm_eo];
        s[1] = '\0';
        inform(_line, _pos, s, "symbol", "");
        yyless(len_s+1);
        _pos += 1;
        regfree(&preg);

    }
    */
/* float [+-]?[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)? */
/*
    ({float}[\+\-\*\/]{float}) {
        regex_t preg;
        regcomp(&preg, "[+-]?[0-9]+(\\.[0-9]+)?([eE][+-]?[0-9]+)?", REG_EXTENDED);
        char text[200], s[200];
        memcpy(text, yytext, (sizeof(char) * 200 > strlen(yytext) ? strlen(yytext) : sizeof(char) * 200));
        regmatch_t matchptr[1];
        int status = regexec(&preg, text, 1, matchptr, 0);
        size_t len_s = 0;
        if (status == 0)
        {
            len_s = matchptr[0].rm_eo - matchptr[0].rm_so;
            memcpy(s, text + matchptr[0].rm_so, len_s * sizeof(char));
        }
        s[len_s] = '\0';
        inform(_line, _pos, s, "float", "");
        _pos += len_s;
        s[0] = text[matchptr[0].rm_eo];
        s[1] = '\0';
        inform(_line, _pos, s, "symbol", "");
        yyless(len_s+1);
        _pos += 1;
        regfree(&preg);
    }
    */
case 6:
YY_RULE_SETUP
#line 178 "B103040012.l"
{
        inform(_line, _pos, yytext, "float", "");
        _pos += yyleng;
        BEGIN(NUMERIC_STATE);
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 184 "B103040012.l"
{
        inform(_line, _pos, yytext, "symbol", "");
        _pos += yyleng;
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 189 "B103040012.l"
{
        yymore();
        BEGIN(COMMENT_STATE);
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 194 "B103040012.l"
{
        char type[50] = "incompleted comment";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The comment is incompleted.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 205 "B103040012.l"
{
        inform(_line, _pos, yytext, "string", "");
        _pos += yyleng;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 210 "B103040012.l"
{
        char type[50] = "invalid identity";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The length exceeds the maximum length.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 221 "B103040012.l"
{
        char type[50] = "invalid identity";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Starts with the invalid character: %s%c%s.", _line, KRED, KWHT, KRED, yytext[0], KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
/*
    {nonid} {
        inform(_line, _pos, yytext, "invalid identity");
        _pos += yyleng;
    }
    */
case 13:
YY_RULE_SETUP
#line 239 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Using double quotation marks (\").", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
/*
    {incompleted_string_dquote} {
        char type[50] = "invalid string";
        color(KRED, type);
        
        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Incompleted string with double quotation marks (\").", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
    */
/*
    i found that gcc does not detect incomplete string: 
    for example, string like 
    ab" 
    will be determined as identity and non-terminated quote.

    {incompleted_string} {
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Incompleted string.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
    */
case 14:
YY_RULE_SETUP
#line 281 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The length exceeds the maximum length.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 293 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s missing terminating ' character.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
/*
    {nonstring} {
        inform(_line, _pos, yytext, "non-string", "");
        _pos += yyleng;
    }
    */
case 16:
YY_RULE_SETUP
#line 311 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The fraction is missing.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 322 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The integer is missing.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 333 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The exponential part cannot have fraction.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
/*
    {float_with_multi_frac} {
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s This float contains multiple fractions.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
    */
/*
    {nonfloat} {
        inform(_line, _pos, yytext, "non-float", "");
        _pos += yyleng;
    }
    */
case 19:
YY_RULE_SETUP
#line 363 "B103040012.l"
{
        char type[50] = "incompleted comment";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The comment is incompleted.", _line, KRED, KWHT);
    }
	YY_BREAK
/*
    {noncomment} {
        char type[50] = "invalid comment";
        color(KRED, type);

        inform(_line, _pos, yytext, "invalid comment", "");
        _pos += yyleng;
    }
    */
case 20:
YY_RULE_SETUP
#line 381 "B103040012.l"
{
        char type[50] = "error";
        color(KRED, type);

        inform(_line, _pos, yytext, "error", "");
        _pos += yyleng;
    }
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 391 "B103040012.l"
{
        _pos += yyleng;
        yymore();
    }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 396 "B103040012.l"
{
        ++_line;
        _pos = 1;
        yymore();
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 402 "B103040012.l"
{
        inform(_line, _pos, yytext, "comment", "");
        BEGIN(INITIAL);
    }
	YY_BREAK


case 24:
YY_RULE_SETUP
#line 409 "B103040012.l"
{
        inform(_line, _pos, yytext, "symbol", "");
        _pos += yyleng;
        BEGIN(INITIAL);
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 415 "B103040012.l"
{
        yyless(0);
        BEGIN(INITIAL);
    }
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 421 "B103040012.l"
ECHO;
	YY_BREAK
#line 1522 "lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_STATE):
case YY_STATE_EOF(NUMERIC_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 353 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 353 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 352);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 421 "B103040012.l"


void color(const char* c, char* s)
{
    char buffer[300];
    sprintf(buffer, "%s%s%s", c, s, KWHT);
    memcpy(s, buffer, strlen(buffer) * sizeof(char));
}

void inform(unsigned long l, unsigned long p, const char* token, const char* type, const char* complement)
{
    printf("Line: %lu, 1st char: %lu, \"%s\" is a \"%s\". %s\n", l, p, token, type, complement);
}

int main()
{
    yylex();
    show_symbol_table();
}

