
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[401] =
    {   0,
        0,    0,   58,   58,    0,    0,   66,   57,    2,    1,
       57,   57,   49,   32,   52,   45,   44,   41,   40,   33,
       36,   41,   30,   34,   35,   39,   39,   39,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   46,   47,   58,
       59,   58,   58,   64,   65,   63,   62,   61,   61,   61,
       64,   64,   64,   64,   64,    1,    0,   50,    0,   49,
       52,   43,   37,   38,    0,    0,   30,   54,   53,   30,
       49,   18,   32,   39,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   11,   42,   42,   42,   42,

       42,    8,   39,   42,   42,   42,   42,   42,   14,   40,
       42,   42,   42,   42,   42,   42,   15,   42,   42,   42,
       42,   42,   42,   58,   59,   58,   60,   58,   61,    0,
        0,   61,    0,   62,   52,   43,    0,   56,    0,    0,
       31,    0,    0,    0,   31,   42,   42,   41,   42,   42,
       42,   42,   42,   42,   42,   42,   41,   42,   42,   42,
       12,   42,    7,   42,   42,   42,   41,    3,   28,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   20,   42,
       42,   42,   42,   63,   63,   63,   52,   43,    0,   31,
        0,   54,    0,   53,   55,   55,   49,   42,   42,   42,

       42,   42,   29,   42,   13,   29,   42,   42,   42,   42,
       42,    9,   42,   42,   42,   42,   42,   42,   42,   27,
       29,   42,   42,   42,   42,   10,   42,   42,   17,   29,
       42,   52,   43,    0,    0,   55,    0,   49,   42,   42,
       26,   23,   24,   42,   42,    3,   42,   42,   42,   29,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   22,   19,   27,   52,   43,    0,   55,   42,   42,
       42,   27,   42,   29,   16,   42,   42,   42,   42,   29,
       42,   42,   21,   42,   29,   29,   42,   52,   43,    0,
       42,   42,   42,   42,   42,   29,   29,   42,   42,    4,

       42,   27,   52,   43,    0,   42,    3,   29,   25,    5,
       29,   42,   29,   52,   43,    0,   42,    6,   52,   43,
        0,   42,   52,   43,    0,   42,   52,   43,    0,   42,
       52,   43,    0,   42,   52,   43,    0,   42,   52,   43,
        0,   42,   52,   43,    0,   48,   52,   43,    0,   48,
       52,   43,    0,   52,   43,    0,   52,   43,    0,   52,
       43,    0,   52,   43,    0,   52,   43,    0,   52,   43,
        0,   52,   43,    0,   52,   43,    0,   52,   43,    0,
       52,   43,    0,   52,   43,    0,   52,   43,    0,   52,
       43,    0,   52,   43,    0,   52,   51,    0,    0,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    6,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   39,   46,   39,
       47,    1,   48,    6,   39,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   39,   65,   66,   67,   68,   69,   70,   39,
       71,   39,   72,    1,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    1,    1,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1
    } ;

static const flex_int16_t yy_base[486] =
    {   0,
        0,    0,   72,   74,   83,  144,  916, 1022, 1022, 1022,
      912,   74,    0, 1022,  902,  898, 1022,   70,   72, 1022,
      887, 1022,   73,  882, 1022,   71,  877,   80,   72,   71,
      120,   76,   89,  134,    0,   91,   47,   78,  117,  158,
       98,  125,  157,  154,  123,  166,  188, 1022, 1022,    0,
     1022,  894,  118, 1022, 1022, 1022, 1022,  109, 1022,  871,
      154,  164,  164,  166,  166, 1022,  222,  227,  883,    0,
      878,  877,  870, 1022,  151,  862,  219,  216,  220,  223,
      240, 1022, 1022, 1022,    0,  198,  196,  201,  213,  222,
      214,  218,  237,  225,  219,  222,  229,  245,  237,  237,

      242,    0,  238,  246,  259,  255,  249,  261,    0,    0,
      257,  275,  259,  263,  261,  276,    0,  264,  267,  278,
      270,  277,  279,    0, 1022,  162, 1022,  317, 1022,  288,
      274, 1022,  295, 1022,  866,  865,  860, 1022,  334,  338,
      306,  346,  194,  850,  339,    0,  301,    0,  318,  313,
      322,  330,  336,  338,  328,  344,    0,  348,  337,  347,
        0,  352,    0,  351,  350,  349,    0,    0,    0,  352,
      365,  355,  353,  344,  353,  356,  360,  366,    0,  378,
      384,  391,  377, 1022, 1022, 1022,  854,  853,  848,  409,
      410,  414,  413,  418,  415,  420,  434,    0,  400,  393,

      414,  419,    0,  422,    0,    0,  431,  414,  426,  424,
      419,    0,  421,  423,  430,  444,  441,  442,  432,    0,
        0,  447,  432,  443,  446,    0,  453,  464,    0,    0,
      466,  847,  842,  841,  490,  483,  494,  501,    0,  455,
        0,    0,    0,  458,  464,    0,  476,  488,  484,    0,
      491,  497,  489,  489,  488,  501,  509,  492,  504,  510,
      510,    0,    0,  506,  836,  835,  830,  529,    0,  500,
      520,    0,  502,    0,    0,  512,  520,  520,  524,    0,
      525,  522,    0,  535,    0,    0,  536,  829,  824,  823,
        0,  546,  540,  549,  541,    0,    0,  552,  540,    0,

      539,    0,  818,  817,  812,    0,    0,    0,    0,    0,
        0,  557,    0,  811,  806,  805,    0,    0,  800,  799,
      794,    0,  793,  788,  787,    0,  782,  781,  776,    0,
      775,  770,  769,    0,  764,  763,  758,    0,  757,  752,
      751,    0,  746,  745,  740,    0,  739,  734,  733,    0,
      728,  727,  722,  721,  716,  715,  710,  709,  704,  703,
      698,  697,  692,  691,  686,  685,  680,  679,  674,  673,
      668,  667,  662,  661,  656,  655,  650,  649,  644,  643,
      637,  634,  631,  626,  625,  622,  617,  616,  601,  600,
      599,  593,  588,  587,  586,  584,  583,  582,  580, 1022,

      610,  616,  622,  625,  631,  580,  637,  643,  649,  573,
      655,  661,  527,  667,  673,  523,  679,  685,  449,  691,
      697,  415,  703,  709,  412,  715,  721,  328,  727,  733,
      324,  739,  745,  273,  751,  757,  256,  763,  769,  214,
      775,  781,  198,  787,  793,  186,  799,  805,  115,  811,
      817,  110,  823,  829,  835,  841,  847,  853,  859,  865,
      871,  877,  883,  889,  895,  901,  907,  913,  919,  925,
      931,  937,  943,  949,  955,  961,  967,  973,  979,  985,
      991,  997, 1003, 1009, 1015
    } ;

static const flex_int16_t yy_def[486] =
    {   0,
      400,    1,  401,  401,  402,  402,  400,  400,  400,  400,
      400,  403,  404,  400,  405,  400,  400,  400,  400,  400,
      400,  400,  404,  400,  400,  400,  400,  400,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  400,  400,  407,
      400,  407,  408,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  403,  403,  400,  404,
      409,  400,  400,  400,  400,  400,  400,  400,  400,  404,
      404,  400,  400,  400,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  407,  400,  408,  400,  408,  400,  400,
      400,  400,  400,  400,  411,  400,  412,  400,  400,  400,
      400,  400,  400,  400,  404,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  400,  400,  400,  414,  400,  415,  400,
      400,  400,  400,  400,  400,  400,  404,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  417,  400,  418,  400,  400,  400,  404,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  420,  400,  421,  400,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  422,  422,  422,  422,  423,  400,  424,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  426,  400,  427,  428,  428,  428,  428,  428,
      428,  428,  428,  429,  400,  430,  431,  431,  432,  400,
      433,  434,  435,  400,  436,  437,  438,  400,  439,  440,
      441,  400,  442,  443,  444,  400,  445,  446,  447,  400,
      448,  449,  450,  400,  451,  452,  453,  400,  454,  452,
      455,  400,  456,  457,  400,  458,  459,  400,  460,  461,
      400,  462,  463,  400,  464,  465,  400,  466,  467,  400,
      468,  469,  400,  470,  471,  400,  472,  473,  400,  474,
      475,  400,  476,  477,  400,  478,  479,  400,  480,  481,
      400,  482,  483,  400,  484,  483,  400,  485,  485,    0,

      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400
    } ;

static const flex_int16_t yy_nxt[1097] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   35,
       36,   35,   35,   37,   38,   39,   40,   41,   35,   42,
       43,   44,   45,   46,   47,   35,   48,   49,   29,   30,
       31,   32,   33,   34,   35,   35,   36,   35,   35,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       35,   14,   14,   14,   51,   52,   51,   52,   68,   74,
       75,   69,   53,  104,   53,   55,   76,   79,   77,   80,
       83,   84,   84,   56,   57,   86,   57,   89,   56,   81,

       84,   83,   58,   59,   60,   61,   95,   87,   62,  104,
       90,   88,   96,   63,  105,  350,   91,   64,  102,   65,
      346,   86,   97,   89,   98,   81,  103,  127,  128,  129,
      129,   61,   95,   87,   62,   90,   88,  111,   96,   63,
      105,   91,   92,   64,  102,   65,   55,  106,   97,   93,
       98,  112,  103,  107,   56,   57,   94,   57,  118,   56,
       74,   75,  111,   58,   59,   60,   61,   99,   92,   62,
      100,  400,  400,  106,   63,   93,  101,  112,   64,  107,
       65,  108,   94,  116,  118,  109,  113,  114,  119,  130,
      117,  342,   61,   99,  131,   62,  100,  110,  115,  132,

       63,  101,  133,  338,   64,  134,   65,  108,  144,  116,
      190,  109,  113,  114,  119,  130,  117,  120,  121,  334,
      131,  148,  110,  115,  122,  132,   68,  123,  133,   69,
      134,   68,   78,   79,   69,   77,  141,   79,  147,   80,
      149,  150,  140,  120,  121,  139,  142,  148,  151,   81,
      122,  143,  123,  143,  144,  152,  145,  153,  154,  155,
      156,  330,  157,  147,  158,  149,  159,  150,  140,  160,
      161,  139,  142,  162,  151,   81,  163,  164,  326,  165,
      152,  166,  153,  154,  167,  155,  156,  157,  168,  158,
      169,  159,  170,  171,  160,  174,  161,  172,  175,  162,

      176,  163,  177,  164,  165,  178,  179,  166,  180,  183,
      167,  181,  173,  184,  168,  169,  182,  185,  170,  171,
      186,  174,  141,  172,  175,  176,  127,  128,  177,  322,
      178,  179,  139,  317,  180,  183,  181,  199,  173,  184,
      200,  182,  185,  201,  202,  143,  186,  143,  144,  191,
      190,  191,  144,  196,  192,  145,  203,  193,  139,  193,
      144,  204,  194,  199,  205,  197,  200,  206,  207,  201,
      202,  210,  211,  212,  213,  214,  215,  216,  217,  222,
      220,  224,  203,  223,  208,  209,  225,  204,  221,  218,
      205,  197,  206,  219,  207,  226,  227,  210,  211,  212,

      213,  214,  215,  216,  217,  222,  220,  224,  223,  208,
      209,  228,  225,  229,  221,  218,  230,  306,  231,  219,
      291,  226,  227,  196,  144,  190,  192,  144,  196,  194,
      192,  195,  196,  240,  194,  235,  236,  228,  241,  229,
      235,  235,  230,  231,  235,  237,  235,  237,  144,  242,
      238,  243,  244,  245,  269,  246,  247,  248,  252,  240,
      249,  235,  250,  241,  251,  255,  235,  235,  256,  258,
      235,  257,  235,  259,  253,  242,  260,  243,  244,  245,
      246,  261,  247,  248,  252,  249,  262,  250,  254,  251,
      263,  255,  264,  271,  256,  258,  257,  270,  259,  236,

      253,  237,  260,  237,  144,  272,  268,  261,  144,  235,
      268,  273,  262,  254,  274,  196,  263,  238,  264,  271,
      275,  276,  270,  277,  278,  279,  281,  197,  239,  280,
      272,  282,  198,  283,  284,  235,  285,  273,  286,  287,
      274,  292,  293,  196,  294,  268,  275,  276,  295,  277,
      278,  279,  281,  197,  280,  235,  300,  282,  283,  296,
      284,  297,  285,  298,  286,  287,  292,  299,  293,  294,
      301,  302,  307,  308,  295,  309,  310,  311,  146,  312,
      313,  235,  300,  318,  296,   85,  297,  397,  298,  397,
      399,  397,  299,  394,  398,  397,  301,  302,  307,  308,

      391,  309,  310,  311,  312,  313,  395,  394,  388,  318,
       50,   50,   50,   50,   50,   50,   54,   54,   54,   54,
       54,   54,   67,  392,  391,   67,   67,   67,   70,  385,
       70,   71,  389,  388,   71,   71,   71,  124,  382,  124,
      124,  386,  124,  126,  385,  126,  126,  126,  126,  135,
      379,  383,  135,  135,  135,  187,  382,  376,  187,  187,
      187,  189,  380,  379,  189,  189,  189,  232,  373,  377,
      232,  232,  232,  234,  376,  370,  234,  234,  234,  265,
      374,  373,  265,  265,  265,  267,  367,  371,  267,  267,
      267,  288,  370,  364,  288,  288,  288,  290,  368,  367,

      290,  290,  290,  303,  361,  365,  303,  303,  303,  305,
      364,  358,  305,  305,  305,  314,  362,  361,  314,  314,
      314,  316,  355,  359,  316,  316,  316,  319,  358,  352,
      319,  319,  319,  321,  356,  355,  321,  321,  321,  323,
      348,  353,  323,  323,  323,  325,  352,  344,  325,  325,
      325,  327,  349,  348,  327,  327,  327,  329,  340,  345,
      329,  329,  329,  331,  344,  336,  331,  331,  331,  333,
      341,  340,  333,  333,  333,  335,  332,  337,  335,  335,
      335,  337,  336,  328,  337,  337,  337,  339,  333,  332,
      339,  339,  339,  341,  324,  329,  341,  341,  341,  343,

      328,  320,  343,  343,  343,  345,  325,  324,  345,  345,
      345,  347,  315,  321,  347,  347,  347,  349,  320,  304,
      349,  349,  349,  351,  316,  315,  351,  351,  351,  353,
      289,  305,  353,  353,  353,  354,  304,  266,  354,  354,
      354,  356,  290,  289,  356,  356,  356,  357,  233,  267,
      357,  357,  357,  359,  266,  188,  359,  359,  359,  360,
      234,  233,  360,  360,  360,  362,  195,  136,  362,  362,
      362,  363,  189,  188,  363,  363,  363,  365,   78,  138,
      365,  365,  365,  366,  137,  136,  366,  366,  366,  368,
       67,  129,  368,  368,  368,  369,  125,   83,  369,  369,

      369,  371,   82,   78,  371,  371,  371,  372,   73,   72,
      372,  372,  372,  374,   66,  400,  374,  374,  374,  375,
      400,  400,  375,  375,  375,  377,  400,  400,  377,  377,
      377,  378,  400,  400,  378,  378,  378,  380,  400,  400,
      380,  380,  380,  381,  400,  400,  381,  381,  381,  383,
      400,  400,  383,  383,  383,  384,  400,  400,  384,  384,
      384,  386,  400,  400,  386,  386,  386,  387,  400,  400,
      387,  387,  387,  389,  400,  400,  389,  389,  389,  390,
      400,  400,  390,  390,  390,  392,  400,  400,  392,  392,
      392,  393,  400,  400,  393,  393,  393,  395,  400,  400,

      395,  395,  395,  396,  400,  400,  396,  396,  396,  398,
      400,  400,  398,  398,  398,  399,  400,  400,  399,  399,
      399,    7,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400

    } ;

static const flex_int16_t yy_chk[1097] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,   12,   18,
       18,   12,    3,   37,    4,    5,   19,   23,   19,   23,
       26,   26,   26,    5,    5,   29,    5,   30,    5,   23,

       28,   28,    5,    5,    5,    5,   32,   29,    5,   37,
       30,   29,   32,    5,   38,  452,   30,    5,   36,    5,
      449,   29,   33,   30,   33,   23,   36,   53,   53,   58,
       58,    5,   32,   29,    5,   30,   29,   41,   32,    5,
       38,   30,   31,    5,   36,    5,    6,   39,   33,   31,
       33,   42,   36,   39,    6,    6,   31,    6,   45,    6,
       75,   75,   41,    6,    6,    6,    6,   34,   31,    6,
       34,  126,  126,   39,    6,   31,   34,   42,    6,   39,
        6,   40,   31,   44,   45,   40,   43,   43,   46,   61,
       44,  446,    6,   34,   62,    6,   34,   40,   43,   63,

        6,   34,   64,  443,    6,   65,    6,   40,  143,   44,
      143,   40,   43,   43,   46,   61,   44,   47,   47,  440,
       62,   87,   40,   43,   47,   63,   67,   47,   64,   67,
       65,   68,   78,   77,   68,   77,   79,   80,   86,   80,
       88,   89,   78,   47,   47,   77,   79,   87,   90,   80,
       47,   81,   47,   81,   81,   91,   81,   92,   92,   93,
       94,  437,   95,   86,   96,   88,   96,   89,   78,   97,
       98,   77,   79,   99,   90,   80,  100,  101,  434,  103,
       91,  104,   92,   92,  105,   93,   94,   95,  106,   96,
      107,   96,  108,  111,   97,  113,   98,  112,  114,   99,

      115,  100,  116,  101,  103,  118,  119,  104,  120,  123,
      105,  121,  112,  130,  106,  107,  122,  131,  108,  111,
      133,  113,  141,  112,  114,  115,  128,  128,  116,  431,
      118,  119,  141,  428,  120,  123,  121,  147,  112,  130,
      149,  122,  131,  150,  151,  139,  133,  139,  139,  140,
      139,  140,  140,  145,  140,  145,  152,  142,  141,  142,
      142,  153,  142,  147,  154,  145,  149,  155,  156,  150,
      151,  158,  159,  160,  162,  164,  165,  166,  170,  173,
      172,  175,  152,  174,  156,  156,  176,  153,  172,  171,
      154,  145,  155,  171,  156,  177,  178,  158,  159,  160,

      162,  164,  165,  166,  170,  173,  172,  175,  174,  156,
      156,  180,  176,  181,  172,  171,  182,  425,  183,  171,
      422,  177,  178,  190,  191,  190,  191,  193,  192,  193,
      192,  195,  194,  199,  194,  190,  196,  180,  200,  181,
      192,  195,  182,  183,  194,  197,  196,  197,  197,  201,
      197,  202,  204,  207,  419,  208,  209,  210,  215,  199,
      211,  190,  213,  200,  214,  217,  192,  195,  218,  222,
      194,  219,  196,  223,  216,  201,  224,  202,  204,  207,
      208,  225,  209,  210,  215,  211,  227,  213,  216,  214,
      228,  217,  231,  244,  218,  222,  219,  240,  223,  236,

      216,  235,  224,  235,  235,  245,  235,  225,  237,  236,
      237,  247,  227,  216,  248,  238,  228,  238,  231,  244,
      249,  251,  240,  252,  253,  254,  256,  238,  416,  255,
      245,  257,  413,  258,  259,  236,  260,  247,  261,  264,
      248,  270,  271,  268,  273,  268,  249,  251,  276,  252,
      253,  254,  256,  238,  255,  268,  282,  257,  258,  277,
      259,  278,  260,  279,  261,  264,  270,  281,  271,  273,
      284,  287,  292,  293,  276,  294,  295,  298,  410,  299,
      301,  268,  282,  312,  277,  406,  278,  399,  279,  398,
      397,  396,  281,  395,  394,  393,  284,  287,  292,  293,

      392,  294,  295,  298,  299,  301,  391,  390,  389,  312,
      401,  401,  401,  401,  401,  401,  402,  402,  402,  402,
      402,  402,  403,  388,  387,  403,  403,  403,  404,  386,
      404,  405,  385,  384,  405,  405,  405,  407,  383,  407,
      407,  382,  407,  408,  381,  408,  408,  408,  408,  409,
      380,  379,  409,  409,  409,  411,  378,  377,  411,  411,
      411,  412,  376,  375,  412,  412,  412,  414,  374,  373,
      414,  414,  414,  415,  372,  371,  415,  415,  415,  417,
      370,  369,  417,  417,  417,  418,  368,  367,  418,  418,
      418,  420,  366,  365,  420,  420,  420,  421,  364,  363,

      421,  421,  421,  423,  362,  361,  423,  423,  423,  424,
      360,  359,  424,  424,  424,  426,  358,  357,  426,  426,
      426,  427,  356,  355,  427,  427,  427,  429,  354,  353,
      429,  429,  429,  430,  352,  351,  430,  430,  430,  432,
      349,  348,  432,  432,  432,  433,  347,  345,  433,  433,
      433,  435,  344,  343,  435,  435,  435,  436,  341,  340,
      436,  436,  436,  438,  339,  337,  438,  438,  438,  439,
      336,  335,  439,  439,  439,  441,  333,  332,  441,  441,
      441,  442,  331,  329,  442,  442,  442,  444,  328,  327,
      444,  444,  444,  445,  325,  324,  445,  445,  445,  447,

      323,  321,  447,  447,  447,  448,  320,  319,  448,  448,
      448,  450,  316,  315,  450,  450,  450,  451,  314,  305,
      451,  451,  451,  453,  304,  303,  453,  453,  453,  454,
      290,  289,  454,  454,  454,  455,  288,  267,  455,  455,
      455,  456,  266,  265,  456,  456,  456,  457,  234,  233,
      457,  457,  457,  458,  232,  189,  458,  458,  458,  459,
      188,  187,  459,  459,  459,  460,  144,  137,  460,  460,
      460,  461,  136,  135,  461,  461,  461,  462,   76,   73,
      462,  462,  462,  463,   72,   71,  463,  463,  463,  464,
       69,   60,  464,  464,  464,  465,   52,   27,  465,  465,

      465,  466,   24,   21,  466,  466,  466,  467,   16,   15,
      467,  467,  467,  468,   11,    7,  468,  468,  468,  469,
        0,    0,  469,  469,  469,  470,    0,    0,  470,  470,
      470,  471,    0,    0,  471,  471,  471,  472,    0,    0,
      472,  472,  472,  473,    0,    0,  473,  473,  473,  474,
        0,    0,  474,  474,  474,  475,    0,    0,  475,  475,
      475,  476,    0,    0,  476,  476,  476,  477,    0,    0,
      477,  477,  477,  478,    0,    0,  478,  478,  478,  479,
        0,    0,  479,  479,  479,  480,    0,    0,  480,  480,
      480,  481,    0,    0,  481,  481,  481,  482,    0,    0,

      482,  482,  482,  483,    0,    0,  483,  483,  483,  484,
        0,    0,  484,  484,  484,  485,    0,    0,  485,  485,
      485,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  400

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "B103040012.l"
#line 2 "B103040012.l"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "y.tab.h"

#define KNRM  "\x1B[0m"
#define KRED  "\x1B[31m"
#define KGRN  "\x1B[32m"
#define KYEL  "\x1B[33m"
#define KBLU  "\x1B[34m"
#define KMAG  "\x1B[35m"
#define KCYN  "\x1B[36m"
#define KWHT  "\x1B[37m"

extern unsigned long _line;
unsigned long _pos = 1, _cppos = 1;

void inform(unsigned long l, unsigned long p, const char* token, const char* type, const char* complement);
void color(const char* c, char* s);
#line 858 "lex.yy.c"
/* float [+-]?[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)? */
/*comments \(\*({comments}|.|\r?\n)?\*\)*/
/* flex cannot “balance” parentheses to an arbitrary degree: https://www.cs.virginia.edu/~cr4bd/flex-manual/Does-flex-support-recursive-pattern-definitions_003f.html */
/* incompleted_string_dquote \"[^;\r\n\ ]*|[^;\r\n\ ]*\" */
/* incompleted_string \'[^)';\r\n\ ]*|[^(';\r\n\ ]*\' */
/* float_with_multi_frac {int}(\.{unsigned}?([eE]({float_without_frac_exp}|{float_without_int_exp}|{float_without_exp}))?){2,} */

#line 866 "lex.yy.c"

#define INITIAL 0
#define COMMENT_STATE 1
#define NUMERIC_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 104 "B103040012.l"


#line 1088 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 401 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1022 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 107 "B103040012.l"
{
        ++_line;
        printf("\nLine %02lu: ", _line);
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "B103040012.l"
{
        _pos += yyleng;
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 116 "B103040012.l"
{
        /*
        char type[50] = "reserved word";
        color(KGRN, type);
        */

        /* inform(_line, _pos, yytext, type, ""); */
        _pos += yyleng;
    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 126 "B103040012.l"
{
        return PROGRAM;
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "B103040012.l"
{
        return FUNCTION;
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 134 "B103040012.l"
{
        return PROCEDURE;
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 138 "B103040012.l"
{
        return FOR;
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 142 "B103040012.l"
{
        return IF;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 146 "B103040012.l"
{
        return ELSE;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 150 "B103040012.l"
{
        return THEN;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 154 "B103040012.l"
{
        return DO;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "B103040012.l"
{
        return END;
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 162 "B103040012.l"
{
        return CASE;
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 166 "B103040012.l"
{
        return OF;
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 170 "B103040012.l"
{
        return TO;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 174 "B103040012.l"
{
        return DOWNTO;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 178 "B103040012.l"
{
        return WITH;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 182 "B103040012.l"
{
        return ASSIGN;
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 186 "B103040012.l"
{
        return WHILE;
    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 190 "B103040012.l"
{
        return VAR;
    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 194 "B103040012.l"
{
        return REPEAT;
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 198 "B103040012.l"
{
        return UNTIL;
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 202 "B103040012.l"
{
        return _BEGIN;
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 206 "B103040012.l"
{
        return BREAK;
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 210 "B103040012.l"
{
        return CONTINUE;
    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 214 "B103040012.l"
{
        return ARRAY;
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "B103040012.l"
{
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return BUILTIN_FUNCTION;
    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 225 "B103040012.l"
{
        return LOGICALNOT;
    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 229 "B103040012.l"
{
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return TYPE;
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 236 "B103040012.l"
{
        _pos += yyleng;
        sscanf(yytext, "%d", &yylval.intVal);
        //printf("detect \"%s\"", yytext);
        BEGIN(NUMERIC_STATE);
        return INT;
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 244 "B103040012.l"
{
        _pos += yyleng;
        sscanf(yytext, "%f", &yylval.floatVal);
        BEGIN(NUMERIC_STATE);
        return FLOAT;
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 251 "B103040012.l"
{
        _pos += yyleng;
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 255 "B103040012.l"
{
        return ',';
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 259 "B103040012.l"
{
        return ':';
    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 263 "B103040012.l"
{
        return ';';
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 267 "B103040012.l"
{
        return '.';
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 271 "B103040012.l"
{
        _cppos = _pos;
        yymore();
        BEGIN(COMMENT_STATE);
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 277 "B103040012.l"
{
        char type[50] = "incompleted comment";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The comment is incompleted.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 288 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return RELATIONAL_OP;
    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 296 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return ADD_OP;
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 304 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return MUL_OP;
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 312 "B103040012.l"
{
        _pos += yyleng;
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        //printf("detect \"%s\"", yytext);
        return ID;
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 321 "B103040012.l"
{
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        BEGIN(NUMERIC_STATE);
        return STRING;
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 329 "B103040012.l"
{
        return ')';
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 333 "B103040012.l"
{
        return '(';
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 337 "B103040012.l"
{
        return '[';
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 341 "B103040012.l"
{
        return ']';
    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 345 "B103040012.l"
{
        char type[50] = "invalid identity";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The length exceeds the maximum length.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 356 "B103040012.l"
{
        char type[50] = "invalid identity";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Starts with the invalid character: %s%c%s.", _line, KRED, KWHT, KRED, yytext[0], KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 367 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Using double quotation marks (\").", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
/*
    i found that gcc does not detect incomplete string: 
    for example, string like 
    ab" 
    will be determined as identity and non-terminated quote.

    {incompleted_string} {
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Incompleted string.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
    */
case 51:
YY_RULE_SETUP
#line 396 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The length exceeds the maximum length.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 408 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s missing terminating ' character.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 419 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The fraction is missing.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 430 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The integer is missing.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 441 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The exponential part cannot have fraction.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 452 "B103040012.l"
{
        char type[50] = "incompleted comment";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The comment is incompleted.", _line, KRED, KWHT);
    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 460 "B103040012.l"
{
        char type[50] = "Error";
        color(KRED, type);

        //inform(_line, _pos, yytext, type, "");
        _pos += yyleng;

        return yytext[0];
    }
	YY_BREAK


case 58:
YY_RULE_SETUP
#line 472 "B103040012.l"
{
        yymore();
    }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 476 "B103040012.l"
{
        ++_line;
        yymore();
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 481 "B103040012.l"
{
        BEGIN(INITIAL);
    }
	YY_BREAK


case 61:
YY_RULE_SETUP
#line 487 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return RELATIONAL_OP;
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 495 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return ADD_OP;
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 503 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        for (char* p = yylval.stringVal; *p; ++p)
            *p = tolower(*p);
        return MUL_OP;
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 511 "B103040012.l"
{
        yyless(0);
        BEGIN(INITIAL);
    }
	YY_BREAK

case 65:
YY_RULE_SETUP
#line 517 "B103040012.l"
ECHO;
	YY_BREAK
#line 1758 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_STATE):
case YY_STATE_EOF(NUMERIC_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 401 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 401 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 400);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 517 "B103040012.l"


void color(const char* c, char* s)
{
    char buffer[300];
    sprintf(buffer, "%s%s%s", c, s, KWHT);
    memcpy(s, buffer, strlen(buffer) * sizeof(char));
}

void inform(unsigned long l, unsigned long p, const char* token, const char* type, const char* complement)
{
    printf("Lex Line: %lu, 1st char: %lu, \"%s\" is a \"%s\". %s\n", l, p, token, type, complement);
}

int yywrap(){
    return 1;
}

/*
int main()
{
    yylex();
    show_symbol_table();
}
*/

