
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[389] =
    {   0,
        0,    0,   56,   56,    0,    0,   64,   55,    2,    1,
       55,   55,   47,   30,   50,   43,   42,   39,   38,   31,
       34,   39,   28,   32,   33,   37,   37,   37,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   44,   45,   56,
       57,   56,   56,   62,   63,   61,   60,   59,   59,   59,
       62,   62,   62,   62,   62,    1,    0,   48,    0,   47,
       50,   41,   35,   36,    0,    0,   28,   52,   51,   28,
       47,   16,   30,   37,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,    9,   40,   40,   40,   40,   40,

        6,   37,   40,   40,   40,   40,   40,   12,   38,   40,
       40,   40,   40,   40,   40,   13,   40,   40,   40,   40,
       40,   40,   56,   57,   56,   58,   56,   59,    0,    0,
       59,    0,   60,   50,   41,    0,   54,    0,    0,   29,
        0,    0,    0,   29,   40,   40,   39,   40,   40,   40,
       40,   40,   40,   40,   39,   40,   40,   40,   10,   40,
        5,   40,   40,   40,   39,    3,   26,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   18,   40,   40,   40,
       40,   61,   61,   61,   50,   41,    0,   29,    0,   52,
        0,   51,   53,   53,   47,   40,   40,   40,   40,   40,

       27,   40,   11,   40,   40,   40,   40,    7,   40,   40,
       40,   40,   40,   40,   25,   27,   40,   40,   40,   40,
        8,   40,   40,   15,   27,   40,   50,   41,    0,    0,
       53,    0,   47,   40,   40,   24,   21,   22,   40,    3,
       40,   40,   40,   27,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   20,   17,   25,   50,   41,    0,
       53,   40,   40,   40,   40,   27,   14,   40,   40,   40,
       40,   27,   40,   19,   40,   27,   27,   40,   50,   41,
        0,   40,   40,   40,   40,   40,   27,   27,   40,    4,
       40,   25,   50,   41,    0,   40,    3,   27,   23,    3,

       27,   27,   50,   41,    0,   40,   50,   41,    0,   40,
       50,   41,    0,   40,   50,   41,    0,   40,   50,   41,
        0,   40,   50,   41,    0,   40,   50,   41,    0,   40,
       50,   41,    0,   46,   50,   41,    0,   46,   50,   41,
        0,   50,   41,    0,   50,   41,    0,   50,   41,    0,
       50,   41,    0,   50,   41,    0,   50,   41,    0,   50,
       41,    0,   50,   41,    0,   50,   41,    0,   50,   41,
        0,   50,   41,    0,   50,   41,    0,   50,   41,    0,
       50,   41,    0,   50,   49,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    6,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   39,   46,   39,
       47,    1,   48,    6,   39,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   39,   65,   66,   67,   68,   69,   70,   39,
       71,   39,   72,    1,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    1,    1,    1,
        1,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1
    } ;

static const flex_int16_t yy_base[474] =
    {   0,
        0,    0,   72,   74,   83,  144,  876, 1007, 1007, 1007,
      868,   74,    0, 1007,  862,  854, 1007,   70,   72, 1007,
      847, 1007,   73,  838, 1007,   71,  837,   80,   72,   71,
       90,   88,   97,  134,    0,   87,   47,   91,  132,  150,
      108,  123,  156,  154,  126,  157,  188, 1007, 1007,    0,
     1007,  850,  119, 1007, 1007, 1007, 1007,  161, 1007,  831,
      149,  172,  172,  172,  159, 1007,  222,  228,  839,    0,
      838,  833,  830, 1007,  210,  818,  199,  205,  214,  222,
      242, 1007, 1007, 1007,    0,  197,  214,  203,  217,  220,
      213,  220,  212,  218,  226,  223,  224,  228,  230,  241,

        0,  237,  245,  256,  249,  246,  252,    0,    0,  253,
      274,  255,  257,  259,  273,    0,  260,  265,  275,  269,
      274,  284,    0, 1007,  310, 1007,  318, 1007,  291,  278,
     1007,  299, 1007,  826,  821,  820, 1007,  338,  342,  317,
      346,  316,  806,  347,    0,  303,    0,  319,  314,  323,
      322,  339,  340,  335,    0,  345,  337,  351,    0,  356,
        0,  355,  354,  353,    0,    0,    0,  356,  355,  360,
      358,  348,  360,  359,  356,  365,    0,  363,  368,  377,
      372, 1007, 1007, 1007,  814,  809,  808,  404,  320,  410,
      411,  415,  416,  417,  433,    0,  401,  394,  400,  405,

        0,  410,    0,  404,  418,  417,  411,    0,  412,  413,
      427,  427,  434,  426,    0,    0,  437,  431,  440,  440,
        0,  447,  456,    0,    0,  460,  803,  802,  797,  478,
      472,  479,  488,    0,  458,    0,    0,    0,  452,    0,
      468,  479,  471,    0,  479,  484,  476,  479,  476,  496,
      479,  491,  496,  495,    0,    0,  493,  796,  791,  790,
      537,    0,  489,  506,  490,    0,    0,  498,  500,  502,
      507,    0,  516,    0,  521,    0,    0,  523,  785,  784,
      779,    0,  533,  528,  536,  530,    0,    0,  541,    0,
      528,    0,  778,  773,  772,    0,    0,    0,    0,    0,

        0,    0,  767,  766,  761,    0,  760,  755,  754,    0,
      749,  748,  743,    0,  742,  737,  736,    0,  731,  730,
      725,    0,  724,  719,  718,    0,  713,  712,  707,    0,
      706,  701,  700,    0,  695,  694,  689,    0,  688,  683,
      682,  677,  676,  671,  670,  665,  664,  659,  658,  653,
      652,  647,  646,  641,  640,  635,  634,  629,  628,  622,
      619,  616,  611,  610,  607,  602,  601,  586,  583,  579,
      576,  574,  573,  572,  571,  570,  568,  567,  566,  565,
      563,  560,  531,  520,  512,  509,  444, 1007,  595,  601,
      607,  610,  616,  411,  622,  628,  634,  381,  640,  646,

      342,  652,  658,  295,  664,  670,  292,  676,  682,  272,
      688,  694,  236,  700,  706,  186,  712,  718,  166,  724,
      730,  155,  736,  742,  146,  748,  754,  137,  760,  766,
      132,  772,  778,  115,  784,  790,  110,  796,  802,  101,
      808,  814,  820,  826,  832,  838,  844,  850,  856,  862,
      868,  874,  880,  886,  892,  898,  904,  910,  916,  922,
      928,  934,  940,  946,  952,  958,  964,  970,  976,  982,
      988,  994, 1000
    } ;

static const flex_int16_t yy_def[474] =
    {   0,
      388,    1,  389,  389,  390,  390,  388,  388,  388,  388,
      388,  391,  392,  388,  393,  388,  388,  388,  388,  388,
      388,  388,  392,  388,  388,  388,  388,  388,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  394,  394,  394,
      394,  394,  394,  394,  394,  394,  394,  388,  388,  395,
      388,  395,  396,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  391,  391,  388,  392,
      397,  388,  388,  388,  388,  388,  388,  388,  388,  392,
      392,  388,  388,  388,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  395,  388,  396,  388,  396,  388,  388,  388,
      388,  388,  388,  399,  388,  400,  388,  388,  388,  388,
      388,  388,  388,  392,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  388,  388,  388,  402,  388,  403,  388,  388,  388,
      388,  388,  388,  388,  392,  404,  404,  404,  404,  404,

      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  405,  388,  406,  388,
      388,  388,  392,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  408,  388,  409,
      388,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  411,  388,
      412,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  414,  388,  415,  416,  416,  416,  416,  416,

      416,  416,  417,  388,  418,  419,  420,  388,  421,  422,
      423,  388,  424,  425,  426,  388,  427,  428,  429,  388,
      430,  431,  432,  388,  433,  434,  435,  388,  436,  437,
      438,  388,  439,  440,  441,  388,  442,  440,  443,  388,
      444,  445,  388,  446,  447,  388,  448,  449,  388,  450,
      451,  388,  452,  453,  388,  454,  455,  388,  456,  457,
      388,  458,  459,  388,  460,  461,  388,  462,  463,  388,
      464,  465,  388,  466,  467,  388,  468,  469,  388,  470,
      471,  388,  472,  471,  388,  473,  473,    0,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388
    } ;

static const flex_int16_t yy_nxt[1082] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   35,
       36,   35,   35,   37,   38,   39,   40,   41,   35,   42,
       43,   44,   45,   46,   47,   35,   48,   49,   29,   30,
       31,   32,   33,   34,   35,   35,   36,   35,   35,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       35,   14,   14,   14,   51,   52,   51,   52,   68,   74,
       75,   69,   53,  103,   53,   55,   76,   79,   77,   80,
       83,   84,   84,   56,   57,   86,   57,   89,   56,   81,

       84,   83,   58,   59,   60,   61,  338,   87,   62,  103,
       90,   88,   92,   63,  101,  334,   91,   64,   94,   65,
      330,   86,  102,   89,   95,   81,   93,  104,  126,  127,
       96,   61,   97,   87,   62,   90,   88,  326,   92,   63,
      101,   91,  322,   64,   94,   65,   55,  110,  102,  111,
       95,  318,   93,  104,   56,   57,   96,   57,   97,   56,
      314,  117,  105,   58,   59,   60,   61,   98,  106,   62,
       99,  310,  110,  107,   63,  111,  100,  108,   64,  118,
       65,  128,  128,  115,  129,  112,  113,  117,  105,  109,
      116,  306,   61,   98,  106,   62,   99,  114,  133,  107,

       63,  100,  130,  108,   64,  118,   65,  131,  132,  115,
      129,  112,  113,   79,  109,   77,  116,  119,  120,   74,
       75,   78,  114,  133,  121,  138,   68,  122,  130,   69,
      140,  139,   68,  131,  132,   69,   79,  146,   80,  147,
      141,  296,  148,  119,  120,  149,  150,  154,   81,  159,
      121,  138,  122,  142,  151,  142,  143,  139,  144,  152,
      153,  155,  146,  158,  160,  147,  141,  148,  156,  161,
      157,  149,  150,  154,   81,  159,  162,  282,  163,  151,
      164,  165,  166,  168,  152,  153,  155,  167,  158,  169,
      160,  172,  173,  156,  161,  157,  170,  262,  174,  175,

      234,  176,  162,  163,  177,  178,  164,  165,  166,  168,
      179,  171,  167,  180,  181,  169,  182,  172,  173,  388,
      388,  183,  170,  174,  184,  175,  176,  126,  127,  177,
      143,  178,  188,  140,  143,  179,  190,  171,  180,  197,
      181,  198,  182,  138,  199,  200,  183,  196,  201,  142,
      184,  142,  143,  189,  188,  189,  143,  191,  190,  191,
      143,  194,  192,  144,  202,  197,  203,  198,  206,  138,
      199,  200,  207,  195,  201,  204,  205,  208,  209,  210,
      211,  212,  213,  214,  217,  215,  145,  218,  219,  220,
      202,  221,  203,  216,  206,  222,  223,  224,  207,  195,

      204,  205,  225,  208,  209,  210,  211,  212,  213,  214,
      217,  215,  218,  226,  219,  220,   85,  221,  194,  216,
      188,  222,  223,  224,  194,  143,  190,  192,  225,  194,
      230,  192,  193,  231,  235,  237,  230,  238,  226,  236,
      239,  230,  230,  230,  232,  240,  232,  143,  241,  233,
      242,  385,  243,  244,  245,  246,  230,  247,  249,  251,
      235,  237,  230,  238,  236,  250,  239,  230,  230,  230,
      240,  248,  252,  253,  241,  254,  242,  243,  244,  245,
      255,  246,  256,  247,  249,  251,  257,  264,  231,  232,
      250,  232,  143,  143,  261,  261,  248,  252,  230,  253,

      263,  254,  194,  265,  233,  266,  255,  267,  256,  268,
      269,  270,  257,  264,  195,  271,  385,  272,  273,  387,
      274,  275,  276,  277,  230,  263,  278,  385,  284,  265,
      283,  266,  285,  267,  286,  268,  269,  270,  382,  287,
      195,  271,  272,  288,  273,  274,  289,  275,  276,  277,
      290,  194,  278,  261,  284,  283,  291,  285,  292,  297,
      286,  298,  299,  230,  287,  300,  301,  386,  288,  302,
      385,  289,  379,  383,  382,  376,  290,  380,  379,  373,
      377,  376,  291,  370,  292,  297,  374,  298,  299,  230,
      373,  300,  301,  367,  302,   50,   50,   50,   50,   50,

       50,   54,   54,   54,   54,   54,   54,   67,  371,  370,
       67,   67,   67,   70,  364,   70,   71,  368,  367,   71,
       71,   71,  123,  361,  123,  123,  365,  123,  125,  364,
      125,  125,  125,  125,  134,  358,  362,  134,  134,  134,
      185,  361,  355,  185,  185,  185,  187,  359,  358,  187,
      187,  187,  227,  352,  356,  227,  227,  227,  229,  355,
      349,  229,  229,  229,  258,  353,  352,  258,  258,  258,
      260,  346,  350,  260,  260,  260,  279,  349,  343,  279,
      279,  279,  281,  347,  346,  281,  281,  281,  293,  340,
      344,  293,  293,  293,  295,  343,  336,  295,  295,  295,

      303,  341,  340,  303,  303,  303,  305,  332,  337,  305,
      305,  305,  307,  336,  328,  307,  307,  307,  309,  333,
      332,  309,  309,  309,  311,  324,  329,  311,  311,  311,
      313,  328,  320,  313,  313,  313,  315,  325,  324,  315,
      315,  315,  317,  316,  321,  317,  317,  317,  319,  320,
      312,  319,  319,  319,  321,  317,  316,  321,  321,  321,
      323,  308,  313,  323,  323,  323,  325,  312,  304,  325,
      325,  325,  327,  309,  308,  327,  327,  327,  329,  294,
      305,  329,  329,  329,  331,  304,  280,  331,  331,  331,
      333,  295,  294,  333,  333,  333,  335,  259,  281,  335,

      335,  335,  337,  280,  228,  337,  337,  337,  339,  260,
      259,  339,  339,  339,  341,  186,  229,  341,  341,  341,
      342,  228,  193,  342,  342,  342,  344,  135,  187,  344,
      344,  344,  345,  186,   78,  345,  345,  345,  347,  137,
      136,  347,  347,  347,  348,  135,   67,  348,  348,  348,
      350,  128,  124,  350,  350,  350,  351,   83,   82,  351,
      351,  351,  353,   78,   73,  353,  353,  353,  354,   72,
       66,  354,  354,  354,  356,  388,  388,  356,  356,  356,
      357,  388,  388,  357,  357,  357,  359,  388,  388,  359,
      359,  359,  360,  388,  388,  360,  360,  360,  362,  388,

      388,  362,  362,  362,  363,  388,  388,  363,  363,  363,
      365,  388,  388,  365,  365,  365,  366,  388,  388,  366,
      366,  366,  368,  388,  388,  368,  368,  368,  369,  388,
      388,  369,  369,  369,  371,  388,  388,  371,  371,  371,
      372,  388,  388,  372,  372,  372,  374,  388,  388,  374,
      374,  374,  375,  388,  388,  375,  375,  375,  377,  388,
      388,  377,  377,  377,  378,  388,  388,  378,  378,  378,
      380,  388,  388,  380,  380,  380,  381,  388,  388,  381,
      381,  381,  383,  388,  388,  383,  383,  383,  384,  388,
      388,  384,  384,  384,  386,  388,  388,  386,  386,  386,

      387,  388,  388,  387,  387,  387,    7,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388
    } ;

static const flex_int16_t yy_chk[1082] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,   12,   18,
       18,   12,    3,   37,    4,    5,   19,   23,   19,   23,
       26,   26,   26,    5,    5,   29,    5,   30,    5,   23,

       28,   28,    5,    5,    5,    5,  440,   29,    5,   37,
       30,   29,   31,    5,   36,  437,   30,    5,   32,    5,
      434,   29,   36,   30,   32,   23,   31,   38,   53,   53,
       33,    5,   33,   29,    5,   30,   29,  431,   31,    5,
       36,   30,  428,    5,   32,    5,    6,   41,   36,   42,
       32,  425,   31,   38,    6,    6,   33,    6,   33,    6,
      422,   45,   39,    6,    6,    6,    6,   34,   39,    6,
       34,  419,   41,   40,    6,   42,   34,   40,    6,   46,
        6,   58,   58,   44,   61,   43,   43,   45,   39,   40,
       44,  416,    6,   34,   39,    6,   34,   43,   65,   40,

        6,   34,   62,   40,    6,   46,    6,   63,   64,   44,
       61,   43,   43,   77,   40,   77,   44,   47,   47,   75,
       75,   78,   43,   65,   47,   77,   67,   47,   62,   67,
       79,   78,   68,   63,   64,   68,   80,   86,   80,   87,
       79,  413,   88,   47,   47,   89,   90,   93,   80,   97,
       47,   77,   47,   81,   91,   81,   81,   78,   81,   92,
       92,   94,   86,   96,   98,   87,   79,   88,   95,   99,
       95,   89,   90,   93,   80,   97,  100,  410,  102,   91,
      103,  104,  105,  107,   92,   92,   94,  106,   96,  110,
       98,  112,  113,   95,   99,   95,  111,  407,  114,  115,

      404,  117,  100,  102,  118,  119,  103,  104,  105,  107,
      120,  111,  106,  121,  122,  110,  129,  112,  113,  125,
      125,  130,  111,  114,  132,  115,  117,  127,  127,  118,
      142,  119,  142,  140,  189,  120,  189,  111,  121,  146,
      122,  148,  129,  140,  149,  150,  130,  401,  151,  138,
      132,  138,  138,  139,  138,  139,  139,  141,  139,  141,
      141,  144,  141,  144,  152,  146,  153,  148,  156,  140,
      149,  150,  157,  144,  151,  154,  154,  158,  160,  162,
      163,  164,  168,  169,  171,  170,  398,  172,  173,  174,
      152,  175,  153,  170,  156,  176,  178,  179,  157,  144,

      154,  154,  180,  158,  160,  162,  163,  164,  168,  169,
      171,  170,  172,  181,  173,  174,  394,  175,  188,  170,
      188,  176,  178,  179,  190,  191,  190,  191,  180,  192,
      188,  192,  193,  194,  197,  199,  190,  200,  181,  198,
      202,  192,  193,  194,  195,  204,  195,  195,  205,  195,
      206,  387,  207,  209,  210,  211,  188,  212,  213,  217,
      197,  199,  190,  200,  198,  214,  202,  192,  193,  194,
      204,  212,  218,  219,  205,  220,  206,  207,  209,  210,
      222,  211,  223,  212,  213,  217,  226,  239,  231,  230,
      214,  230,  230,  232,  230,  232,  212,  218,  231,  219,

      235,  220,  233,  241,  233,  242,  222,  243,  223,  245,
      246,  247,  226,  239,  233,  248,  386,  249,  250,  385,
      251,  252,  253,  254,  231,  235,  257,  384,  264,  241,
      263,  242,  265,  243,  268,  245,  246,  247,  383,  269,
      233,  248,  249,  270,  250,  251,  271,  252,  253,  254,
      273,  261,  257,  261,  264,  263,  275,  265,  278,  283,
      268,  284,  285,  261,  269,  286,  289,  382,  270,  291,
      381,  271,  380,  379,  378,  377,  273,  376,  375,  374,
      373,  372,  275,  371,  278,  283,  370,  284,  285,  261,
      369,  286,  289,  368,  291,  389,  389,  389,  389,  389,

      389,  390,  390,  390,  390,  390,  390,  391,  367,  366,
      391,  391,  391,  392,  365,  392,  393,  364,  363,  393,
      393,  393,  395,  362,  395,  395,  361,  395,  396,  360,
      396,  396,  396,  396,  397,  359,  358,  397,  397,  397,
      399,  357,  356,  399,  399,  399,  400,  355,  354,  400,
      400,  400,  402,  353,  352,  402,  402,  402,  403,  351,
      350,  403,  403,  403,  405,  349,  348,  405,  405,  405,
      406,  347,  346,  406,  406,  406,  408,  345,  344,  408,
      408,  408,  409,  343,  342,  409,  409,  409,  411,  341,
      340,  411,  411,  411,  412,  339,  337,  412,  412,  412,

      414,  336,  335,  414,  414,  414,  415,  333,  332,  415,
      415,  415,  417,  331,  329,  417,  417,  417,  418,  328,
      327,  418,  418,  418,  420,  325,  324,  420,  420,  420,
      421,  323,  321,  421,  421,  421,  423,  320,  319,  423,
      423,  423,  424,  317,  316,  424,  424,  424,  426,  315,
      313,  426,  426,  426,  427,  312,  311,  427,  427,  427,
      429,  309,  308,  429,  429,  429,  430,  307,  305,  430,
      430,  430,  432,  304,  303,  432,  432,  432,  433,  295,
      294,  433,  433,  433,  435,  293,  281,  435,  435,  435,
      436,  280,  279,  436,  436,  436,  438,  260,  259,  438,

      438,  438,  439,  258,  229,  439,  439,  439,  441,  228,
      227,  441,  441,  441,  442,  187,  186,  442,  442,  442,
      443,  185,  143,  443,  443,  443,  444,  136,  135,  444,
      444,  444,  445,  134,   76,  445,  445,  445,  446,   73,
       72,  446,  446,  446,  447,   71,   69,  447,  447,  447,
      448,   60,   52,  448,  448,  448,  449,   27,   24,  449,
      449,  449,  450,   21,   16,  450,  450,  450,  451,   15,
       11,  451,  451,  451,  452,    7,    0,  452,  452,  452,
      453,    0,    0,  453,  453,  453,  454,    0,    0,  454,
      454,  454,  455,    0,    0,  455,  455,  455,  456,    0,

        0,  456,  456,  456,  457,    0,    0,  457,  457,  457,
      458,    0,    0,  458,  458,  458,  459,    0,    0,  459,
      459,  459,  460,    0,    0,  460,  460,  460,  461,    0,
        0,  461,  461,  461,  462,    0,    0,  462,  462,  462,
      463,    0,    0,  463,  463,  463,  464,    0,    0,  464,
      464,  464,  465,    0,    0,  465,  465,  465,  466,    0,
        0,  466,  466,  466,  467,    0,    0,  467,  467,  467,
      468,    0,    0,  468,  468,  468,  469,    0,    0,  469,
      469,  469,  470,    0,    0,  470,  470,  470,  471,    0,
        0,  471,  471,  471,  472,    0,    0,  472,  472,  472,

      473,    0,    0,  473,  473,  473,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "B103040012.l"
#line 2 "B103040012.l"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "y.tab.h"

#define KNRM  "\x1B[0m"
#define KRED  "\x1B[31m"
#define KGRN  "\x1B[32m"
#define KYEL  "\x1B[33m"
#define KBLU  "\x1B[34m"
#define KMAG  "\x1B[35m"
#define KCYN  "\x1B[36m"
#define KWHT  "\x1B[37m"

extern unsigned long _line;
unsigned long _pos = 1, _cppos = 1;

void inform(unsigned long l, unsigned long p, const char* token, const char* type, const char* complement);
void color(const char* c, char* s);
#line 850 "lex.yy.c"
/* float [+-]?[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)? */
/*comments \(\*({comments}|.|\r?\n)?\*\)*/
/* flex cannot “balance” parentheses to an arbitrary degree: https://www.cs.virginia.edu/~cr4bd/flex-manual/Does-flex-support-recursive-pattern-definitions_003f.html */
/* incompleted_string_dquote \"[^;\r\n\ ]*|[^;\r\n\ ]*\" */
/* incompleted_string \'[^)';\r\n\ ]*|[^(';\r\n\ ]*\' */
/* float_with_multi_frac {int}(\.{unsigned}?([eE]({float_without_frac_exp}|{float_without_int_exp}|{float_without_exp}))?){2,} */

#line 858 "lex.yy.c"

#define INITIAL 0
#define COMMENT_STATE 1
#define NUMERIC_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 104 "B103040012.l"


#line 1080 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 389 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1007 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 107 "B103040012.l"
{
        ++_line;
        printf("\nLine %02lu: ", _line);
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "B103040012.l"
{
        _pos += yyleng;
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 116 "B103040012.l"
{
        /*
        char type[50] = "reserved word";
        color(KGRN, type);
        */

        /* inform(_line, _pos, yytext, type, ""); */
        _pos += yyleng;
    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 126 "B103040012.l"
{
        return PROGRAM;
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 130 "B103040012.l"
{
        return FOR;
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 134 "B103040012.l"
{
        return IF;
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 138 "B103040012.l"
{
        return ELSE;
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 142 "B103040012.l"
{
        return THEN;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 146 "B103040012.l"
{
        return DO;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 150 "B103040012.l"
{
        return END;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 154 "B103040012.l"
{
        return CASE;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "B103040012.l"
{
        return OF;
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 162 "B103040012.l"
{
        return TO;
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 166 "B103040012.l"
{
        return DOWNTO;
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 170 "B103040012.l"
{
        return WITH;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 174 "B103040012.l"
{
        return ASSIGN;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 178 "B103040012.l"
{
        return WHILE;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 182 "B103040012.l"
{
        return VAR;
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 186 "B103040012.l"
{
        return REPEAT;
    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 190 "B103040012.l"
{
        return UNTIL;
    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 194 "B103040012.l"
{
        return _BEGIN;
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 198 "B103040012.l"
{
        return BREAK;
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 202 "B103040012.l"
{
        return CONTINUE;
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 206 "B103040012.l"
{
        return ARRAY;
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 210 "B103040012.l"
{
        yylval.stringVal = strdup(yytext);
        return BUILTIN_FUNCTION;
    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 215 "B103040012.l"
{
        return LOGICALNOT;
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 219 "B103040012.l"
{
        yylval.stringVal = strdup(yytext);
        return TYPE;
    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 224 "B103040012.l"
{
        _pos += yyleng;
        sscanf(yytext, "%d", &yylval.intVal);
        //printf("detect \"%s\"", yytext);
        BEGIN(NUMERIC_STATE);
        return INT;
    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 232 "B103040012.l"
{
        _pos += yyleng;
        sscanf(yytext, "%f", &yylval.floatVal);
        BEGIN(NUMERIC_STATE);
        return FLOAT;
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 239 "B103040012.l"
{
        _pos += yyleng;
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 243 "B103040012.l"
{
        return ',';
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 247 "B103040012.l"
{
        return ':';
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 251 "B103040012.l"
{
        return ';';
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 255 "B103040012.l"
{
        return '.';
    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 259 "B103040012.l"
{
        _cppos = _pos;
        yymore();
        BEGIN(COMMENT_STATE);
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 265 "B103040012.l"
{
        char type[50] = "incompleted comment";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The comment is incompleted.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 276 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        return RELATIONAL_OP;
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 282 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        return ADD_OP;
    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 288 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        return MUL_OP;
    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 294 "B103040012.l"
{
        _pos += yyleng;
        yylval.stringVal = strdup(yytext);
        //printf("detect \"%s\"", yytext);
        return ID;
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 301 "B103040012.l"
{
        yylval.stringVal = strdup(yytext);
        BEGIN(NUMERIC_STATE);
        return STRING;
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 307 "B103040012.l"
{
        return ')';
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 311 "B103040012.l"
{
        return '(';
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 315 "B103040012.l"
{
        return '[';
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 319 "B103040012.l"
{
        return ']';
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 323 "B103040012.l"
{
        char type[50] = "invalid identity";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The length exceeds the maximum length.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 334 "B103040012.l"
{
        char type[50] = "invalid identity";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Starts with the invalid character: %s%c%s.", _line, KRED, KWHT, KRED, yytext[0], KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 345 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Using double quotation marks (\").", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
/*
    i found that gcc does not detect incomplete string: 
    for example, string like 
    ab" 
    will be determined as identity and non-terminated quote.

    {incompleted_string} {
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s Incompleted string.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
    */
case 49:
YY_RULE_SETUP
#line 374 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The length exceeds the maximum length.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 386 "B103040012.l"
{
        char type[50] = "invalid string";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s missing terminating ' character.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 397 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The fraction is missing.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 408 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The integer is missing.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 419 "B103040012.l"
{
        char type[50] = "invalid float type";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The exponential part cannot have fraction.", _line, KRED, KWHT);

        inform(_line, _pos, yytext, type, complement);
        _pos += yyleng;
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 430 "B103040012.l"
{
        char type[50] = "incompleted comment";
        color(KRED, type);

        char complement[100];
        sprintf(complement, "\n%5lu | %sERROR:%s The comment is incompleted.", _line, KRED, KWHT);
    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 438 "B103040012.l"
{
        char type[50] = "Error";
        color(KRED, type);

        inform(_line, _pos, yytext, type, "");
        _pos += yyleng;
    }
	YY_BREAK


case 56:
YY_RULE_SETUP
#line 448 "B103040012.l"
{
        yymore();
    }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 452 "B103040012.l"
{
        ++_line;
        yymore();
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 457 "B103040012.l"
{
        BEGIN(INITIAL);
    }
	YY_BREAK


case 59:
YY_RULE_SETUP
#line 463 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        return RELATIONAL_OP;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 469 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        return ADD_OP;
    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 475 "B103040012.l"
{
        BEGIN(INITIAL);
        yylval.stringVal = strdup(yytext);
        return MUL_OP;
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 481 "B103040012.l"
{
        yyless(0);
        BEGIN(INITIAL);
    }
	YY_BREAK

case 63:
YY_RULE_SETUP
#line 487 "B103040012.l"
ECHO;
	YY_BREAK
#line 1714 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_STATE):
case YY_STATE_EOF(NUMERIC_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 389 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 389 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 388);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 487 "B103040012.l"


void color(const char* c, char* s)
{
    char buffer[300];
    sprintf(buffer, "%s%s%s", c, s, KWHT);
    memcpy(s, buffer, strlen(buffer) * sizeof(char));
}

void inform(unsigned long l, unsigned long p, const char* token, const char* type, const char* complement)
{
    printf("Line: %lu, 1st char: %lu, \"%s\" is a \"%s\". %s\n", l, p, token, type, complement);
}

int yywrap(){
    return 1;
}

/*
int main()
{
    yylex();
    show_symbol_table();
}
*/

